# Generated by Django 4.0.1 on 2022-01-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apijunior', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
