# Generated by Django 4.0.1 on 2022-01-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apijunior', '0002_remove_image_image_image_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='user_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apijunior.user'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apijunior.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
